name: Deploy Flask API to Azure Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r flask-api/requirements.txt
    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      with:
        app-name: 'recommendme'
        package: 'flask-api'
        publish-profile: ${% raw %}{{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}{% endraw %}
